---
- name: prereq install a list of packages for docker engine
  apt:
    update_cache: yes
    state: latest
    pkg:
      - curl
      - ca-certificates
      - gnupg
      - lsb-release

- name: create keyring directory
  file:
    path: /etc/apt/keyrings
    state: directory

- name: download and add docker official gpg to keyring
  shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

- name: generate sources.list for docker
  template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list
  become: true

- name: install a list of packages for docker engine
  apt:
    update_cache: yes
    state: latest
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
