---
- name: install required packages
  apt:
    update_cache: True
    pkg:
    - wget
    - coreutils
    - gpg

- name: add hashicorp gpg
  block:
    - name: hashicorp | add keyring
      ansible.builtin.apt_key:
        id: AA16FCBCA621E701
        url: https://apt.releases.hashicorp.com/gpg
        keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg

    - name: hashicorp | apt source
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }}  main"
        state: present

- name: install nomad
  apt:
    update_cache: True
    pkg:
    - nomad
